LOCATION_MAPPING = {
	--The Hub
	[99250000] = { "@The Hub/The Hub/Book: Lifestyles of the Pharaohs" },
	[99250001] = { "@The Hub/The Hub/Book: Professor's Diary" },
	[99250002] = { "@The Hub/The Hub/Chalice Reward: Cane Stick" },
	[99250003] = { "@The Hub/The Hub/Chalice Reward: Hammer" },
	[99250004] = { "@The Hub/The Hub/Chalice Reward: Crossbow" },
	[99250005] = { "@The Hub/The Hub/Chalice Reward: Axe" },
	[99250006] = { "@The Hub/The Hub/Chalice Reward: Bombs" },
	[99250007] = { "@The Hub/The Hub/Chalice Reward: Broad Sword" },
	[99250008] = { "@The Hub/The Hub/Chalice Reward: Lightning" },
	[99250009] = { "@The Hub/The Hub/Chalice Reward: Blunderbuss" },
	[99250010] = { "@The Hub/The Hub/Chalice Reward: Magic Sword" },
	[99250011] = { "@The Hub/The Hub/Chalice Reward: Gatling Gun" },


	--The Museum
	[99251000] = { "@The Museum/The Museum Part 1/Key Item: Museum Key - TM" },
	[99251001] = { "@The Museum/The Museum Part 1/Key Item: Cannonball - TM" },
	[99251002] = { "@The Museum/The Museum Part 1/Key Item: Torch - TM" },
	[99251003] = { "@The Museum/The Museum Part 1/Key Item: Dinosaur Key - TM" },
	[99251004] = { "@The Museum/The Museum Part 1/Equipment: Short Sword at Start - TM" },
	[99251005] = { "@The Museum/The Museum Part 1/Equipment: Pistol in Case - TM" },
	[99251006] = { "@The Museum/The Museum Part 1/Equipment: Copper Shield 2nd Floor Chest - TM" },
	[99251007] = { "@The Museum/The Museum Part 1/Equipment: Copper Shield Zarok Room - TM" },
	[99251008] = { "@The Museum/The Museum Part 1/Energy Vial: Pistol Room - TM" },
	[99251009] = { "@The Museum/The Museum Part 1/Energy Vial: Mausoleum Room 2nd Floor - TM" },
	[99251010] = { "@The Museum/The Museum Part 1/Energy Vial: Second Hand Room - TM" },
	[99251011] = { "@The Museum/The Museum Part 1/Gold Coins: Hidden Behind Purple Structure - TM" },
	[99251012] = { "@The Museum/The Museum Part 1/Gold Coins: Mausoleum Room 2nd Floor 1 - TM" },
	[99251013] = { "@The Museum/The Museum Part 1/Gold Coins: Mausoleum Room 2nd Floor 2 - TM" },
	[99251014] = { "@The Museum/The Museum Part 1/Gold Coins: Mausoleum Room 2nd Floor 3 - TM" },
	[99251015] = { "@The Museum/The Museum Part 1/Gold Coins: Buddah Statue Staircase - TM" },
	[99251016] = { "@The Museum/The Museum Part 1/Gold Coins: Display Room Balcony Right - TM" },
	[99251017] = { "@The Museum/The Museum Part 1/Gold Coins: Display Room Balcony Left - TM" },
	[99251018] = { "@The Museum/The Museum Part 1/Gold Coins: Zarok Room Rafters Back - TM" },
	[99251019] = { "@The Museum/The Museum Part 1/Gold Coins: Zarok Room Rafters Left - TM" },
	[99251020] = { "@The Museum/The Museum Part 1/Gold Coins: Zarok Room Rafters Right - TM" },
	[99251021] = { "@The Museum/The Museum Part 2/Gold Coins: Tomb Room Left - TM" },
	[99251022] = { "@The Museum/The Museum Part 2/Gold Coins: Tomb Room Right - TM" },
	[99251023] = { "@The Museum/The Museum Part 2/Gold Coins: First Hand Room - Chest 1 - TM" },
	[99251024] = { "@The Museum/The Museum Part 2/Gold Coins: First Hand Room - Chest 2 - TM" },
	[99251025] = { "@The Museum/The Museum Part 2/Gold Coins: First Hand Room - Chest 3 - TM" },
	[99251026] = { "@The Museum/The Museum Part 2/Gold Coins: Second Hand Room - Chest Right of Vial - TM" },
	[99251027] = { "@The Museum/The Museum Part 2/Gold Coins: Second Hand Room - Chest Left of Vial - TM" },
	[99251028] = { "@The Museum/The Museum Part 2/Gold Coins: Second Hand Room - Chest Between Boxes - TM" },
	[99251029] = { "@The Museum/The Museum Part 2/Gold Coins: Second Hand Room - Chest Hidden on Pipes - TM" },
	[99251030] = { "@The Museum/The Museum Part 2/Gold Coins: Second Hand Room - Chest on Boxes - TM" },
	[99251031] = { "@The Museum/The Museum Part 2/Book: Sir Dan - TM" },
	[99251032] = { "@The Museum/The Museum Part 2/Book: The Kraken - TM" },
	[99251033] = { "@The Museum/The Museum Part 2/Book: Zarok - TM" },
	[99251034] = { "@The Museum/The Museum Part 2/Winston: Dans Room - TM" },
	[99251035] = { "@The Museum/The Museum Part 2/Winston: Pistol Room - TM" },
	[99251036] = { "@The Museum/The Museum Part 2/Winston: Chest on Mausoleum Room 2nd Floor - TM" },
	[99251037] = { "@The Museum/The Museum Part 2/Winston: Gold Coins on Mausoleum Room 2nd Floor - TM" },
	[99251038] = { "@The Museum/The Museum Part 2/Winston: Climbing Wall - TM" },
	[99251039] = { "@The Museum/The Museum Part 2/Winston: Staircase After Buddah - TM" },
	[99251040] = { "@The Museum/The Museum Part 2/Winston: Chalice - TM" },
	[99251041] = { "@The Museum/The Museum Part 2/Chalice: The Museum" },
	[99251042] = { "@The Museum/The Museum Part 2/Cleared: The Museum" },

	--Tyrannosaurus Wrecks
	[99252000] = { "@Tyrannosaurus Wrecks/Tyranno/Life Bottle: Tyrannosaurus Wrecks" },
	[99252001] = { "@Tyrannosaurus Wrecks/Tyranno/Equipment: Copper Chest in Stairway - TW" },
	[99252002] = { "@Tyrannosaurus Wrecks/Tyranno/Gold Coins: Bag Behind Lion Statue - TW" },
	[99252003] = { "@Tyrannosaurus Wrecks/Tyranno/Gold Coins: Near Spiv on Stairway - TW" },
	[99252004] = { "@Tyrannosaurus Wrecks/Tyranno/Book: Dinosaur Display - TW" },
	[99252005] = { "@Tyrannosaurus Wrecks/Tyranno/Winston: Entrance - TW" },
	[99252006] = { "@Tyrannosaurus Wrecks/Tyranno/Cleared: Tyrannosaurus Wrecks" },

	--Kensington
	[99253000] = { "@Kensington/Kensington/Key Item: The Depot Key" },
	[99253001] = { "@Kensington/Kensington/Key Item: Town House Key" },
	[99253002] = { "@Kensington/Kensington/Key Item: Pocketwatch" },
	[99253003] = { "@Kensington/Kensington/Equipment: Copper Shield on Railway - KT" },
	[99253004] = { "@Kensington/Kensington/Gold Coins: Bag Near Water in Quayside Mill - KT" },
	[99253005] = { "@Kensington/Kensington/Winston: Pushing and Pulling - KT" },
	[99253006] = { "@Kensington/Kensington/Winston: Where the Spell was Cast - KT" },
	[99253007] = { "@Kensington/Kensington/Winston: Museum Roof - KT" },
	[99253008] = { "@Kensington/Kensington/Chalice: Kensington - KT" },
	[99253009] = { "@Kensington/Kensington/Cleared: Kensington" },

	--The Tomb
	[99254000] = { "@The Tomb/The Tomb/Key Item: Scroll of Sekhmet" },
	[99254001] = { "@The Tomb/The Tomb/Key Item: Tablet of Horus" },
	[99254002] = { "@The Tomb/The Tomb/Key Item: Staff of Anubis" },
	[99254003] = { "@The Tomb/The Tomb/Gold Coins: Tomb Entrance Top Right - TT" },
	[99254004] = { "@The Tomb/The Tomb/Gold Coins: Tomb Entrance Top Left - TT" },
	[99254005] = { "@The Tomb/The Tomb/Gold Coins: Hand Area Chest Ground Floor - TT" },
	[99254006] = { "@The Tomb/The Tomb/Gold Coins: Hand Area Chest Upper Floor - TT" },
	[99254007] = { "@The Tomb/The Tomb/Winston: Entrance - TT" },
	[99254008] = { "@The Tomb/The Tomb/Cleared: The Tomb" },

	--The Freakshow
	[99255000] = { "@The Freakshow/Freakshow/Key Item: Elephant key 1 - TF" },
	[99255001] = { "@The Freakshow/Freakshow/Key Item: Elephant key 2 - TF" },
	[99255002] = { "@The Freakshow/Freakshow/Life Bottle: The Freakshow" },
	[99255003] = { "@The Freakshow/Freakshow/Equipment: Copper Shield in Chalice Room - TF" },
	[99255004] = { "@The Freakshow/Freakshow/Equipment: Copper Shield in Elephant Boss Arena - TF" },
	[99255005] = { "@The Freakshow/Freakshow/Gold Coins: Bag at Start Left - TF" },
	[99255006] = { "@The Freakshow/Freakshow/Gold Coins: Ladies Bag Trap 1 - TF" },
	[99255007] = { "@The Freakshow/Freakshow/Gold Coins: Ladies Bag Trap 2 - TF" },
	[99255008] = { "@The Freakshow/Freakshow/Gold Coins: Ladies Bag Trap 3 - TF" },
	[99255009] = { "@The Freakshow/Freakshow/Gold Coins: Ladies Bag Trap 4 - TF" },
	[99255010] = { "@The Freakshow/Freakshow/Gold Coins: Bag in Tunnel - TF" },
	[99255011] = { "@The Freakshow/Freakshow/Gold Coins: Bag Outside Tunnel - TF" },
	[99255012] = { "@The Freakshow/Freakshow/Gold Coins: Chest at Water Jump - TF" },
	[99255013] = { "@The Freakshow/Freakshow/Gold Coins: Chest Below Giant Clown - TF" },
	[99255014] = { "@The Freakshow/Freakshow/Gold Coins: Chest Hidden at Trampolines - TF" },
	[99255015] = { "@The Freakshow/Freakshow/Gold Coins: Hand Area Chest - TF" },
	[99255016] = { "@The Freakshow/Freakshow/Gold Coins: Hand Area Hidden Chest Left - TF" },
	[99255017] = { "@The Freakshow/Freakshow/Gold Coins: Hand Area Hidden Chest Right - TF" },
	[99255018] = { "@The Freakshow/Freakshow/Winston: Entrance - TF" },
	[99255019] = { "@The Freakshow/Freakshow/Winston: Trampoline - TF" },
	[99255020] = { "@The Freakshow/Freakshow/Winston: Elephant Army - TF" },
	[99255021] = { "@The Freakshow/Freakshow/Chalice: The Freakshow - TF" },
	[99255022] = { "@The Freakshow/Freakshow/Cleared: The Freakshow" },

	--Greenwich Observatory
	[99256000] = { "@Greenwich Observatory/Observatory/Life Bottle: Greenwich Observatory" },
	[99256001] = { "@Greenwich Observatory/Observatory/Equipment: Copper Shield near Bomb Chest" },
	[99256002] = { "@Greenwich Observatory/Observatory/Gold Coins: Fountain Bag 1 - GO" },
	[99256003] = { "@Greenwich Observatory/Observatory/Gold Coins: Fountain Bag 2 - GO" },
	[99256004] = { "@Greenwich Observatory/Observatory/Gold Coins: Bag Below Spiv - GO" },
	[99256005] = { "@Greenwich Observatory/Observatory/Gold Coins: Bag Below Chalice 1 - GO" },
	[99256006] = { "@Greenwich Observatory/Observatory/Gold Coins: Bag Below Chalice 2 - GO" },
	[99256007] = { "@Greenwich Observatory/Observatory/Gold Coins: Chest Near Exit - GO" },
	[99256008] = { "@Greenwich Observatory/Observatory/Gold Coins: Hand Area Chest 1 - GO" },
	[99256009] = { "@Greenwich Observatory/Observatory/Gold Coins: Hand Area Chest 2 - GO" },
	[99256010] = { "@Greenwich Observatory/Observatory/Gold Coins: Hand Area Chest 3 - GO" },
	[99256011] = { "@Greenwich Observatory/Observatory/Winston: Lost your head? - GO" },
	[99256012] = { "@Greenwich Observatory/Observatory/Winston: Close To Ladder - GO" },
	[99256013] = { "@Greenwich Observatory/Observatory/Winston: Lever Puzzle - GO" },
	[99256014] = { "@Greenwich Observatory/Observatory/Winston: Once Through This Door - GO" },
	[99256015] = { "@Greenwich Observatory/Observatory/Chalice: Greenwhich Observatory" },
	[99256016] = { "@Greenwich Observatory/Observatory/Cleared: Greenwich Observatory" },

	--Greenwich, Naval Academy
	[99257000] = { "@Greenwich, Naval Academy/Academy/Key Item: Bellows - GONA" },
	[99257001] = { "@Greenwich, Naval Academy/Academy/Energy Vial: Near Trees - GONA" },
	[99257002] = { "@Greenwich, Naval Academy/Academy/Gold Coins: Bag Near Trees - GONA" },
	[99257003] = { "@Greenwich, Naval Academy/Academy/Winston: Entrance - GONA" },
	[99257004] = { "@Greenwich, Naval Academy/Academy/Cleared: Naval Academy" },

	--Kew Gardens
	[99258000] = { "@Kew Gardens/Gardens/Key Item: Potting Shed Key" },
	[99258001] = { "@Kew Gardens/Gardens/Key Item: Water Tank Valve - KG" },
	[99258002] = { "@Kew Gardens/Gardens/Key Item: Pond Room Valve - KG" },
	[99258003] = { "@Kew Gardens/Gardens/Key Item: Hot House Valve - KG" },
	[99258004] = { "@Kew Gardens/Gardens/Life Bottle: Kew Gardens" },
	[99258005] = { "@Kew Gardens/Gardens/Equipment: Silver Shield in Gauntlet Room - KG" },
	[99258006] = { "@Kew Gardens/Gardens/Energy Vial: Behind Fence Vial 1 - KG" },
	[99258007] = { "@Kew Gardens/Gardens/Energy Vial: Behind Fence Vial 2 - KG" },
	[99258008] = { "@Kew Gardens/Gardens/Gold Coins: Behind Fence Chest 1 - KG" },
	[99258009] = { "@Kew Gardens/Gardens/Gold Coins: Behind Fence Chest 2 - KG" },
	[99258010] = { "@Kew Gardens/Gardens/Gold Coins: Bag Near Shed - KG" },
	[99258011] = { "@Kew Gardens/Gardens/Gold Coins: Chest at Top of Tree in First Human Room - KG" },
	[99258012] = { "@Kew Gardens/Gardens/Gold Coins: Bridge Room Vine Chest 1 - KG" },
	[99258013] = { "@Kew Gardens/Gardens/Gold Coins: Bridge Room Vine Chest 2 - KG" },
	[99258014] = { "@Kew Gardens/Gardens/Gold Coins: Bag Up Tree in Second Human Room - KG" },
	[99258015] = { "@Kew Gardens/Gardens/Gold Coins: Bag on Roof 1 - KG" },
	[99258016] = { "@Kew Gardens/Gardens/Gold Coins: Bag on Roof 2 - KG" },
	[99258017] = { "@Kew Gardens/Gardens/Gold Coins: Bag in Third Human Room - KG" },
	[99258018] = { "@Kew Gardens/Gardens/Gold Coins: Hand Maze Chest - KG" },
	[99258019] = { "@Kew Gardens/Gardens/Gold Coins: Hand Maze Chest Reward 1 - KG" },
	[99258020] = { "@Kew Gardens/Gardens/Gold Coins: Hand Maze Chest Reward 2- KG" },
	[99258021] = { "@Kew Gardens/Gardens/Gold Coins: Hand Maze Chest Reward 3 - KG" },
	[99258022] = { "@Kew Gardens/Gardens/Winston: Level Start - KG" },
	[99258023] = { "@Kew Gardens/Gardens/Winston: Infection - KG" },
	[99258024] = { "@Kew Gardens/Gardens/Chalice: Kew Gardens" },
	[99258025] = { "@Kew Gardens/Gardens/Cleared: Kew Gardens" },

	--Dankenstein
	[99259000] = { "@Dankenstein/Dankenstein/Key Item: Bum - DK" },
	[99259001] = { "@Dankenstein/Dankenstein/Key Item: Left Arm - DK" },
	[99259002] = { "@Dankenstein/Dankenstein/Key Item: Left Leg - DK" },
	[99259003] = { "@Dankenstein/Dankenstein/Key Item: Right Arm - DK" },
	[99259004] = { "@Dankenstein/Dankenstein/Key Item: Right Leg - DK" },
	[99259005] = { "@Dankenstein/Dankenstein/Key Item: Torso - DK" },
	[99259006] = { "@Dankenstein/Dankenstein/Life Bottle: Dankenstein - DK" },
	[99259007] = { "@Dankenstein/Dankenstein/Equipment: Silver shield - DK" },
	[99259008] = { "@Dankenstein/Dankenstein/Gold Coins: Chest Above Projector - DK" },
	[99259009] = { "@Dankenstein/Dankenstein/Gold Coins: Hand Area Chest 1 - DK" },
	[99259010] = { "@Dankenstein/Dankenstein/Gold Coins: Hand Area Chest 2 - DK" },
	[99259011] = { "@Dankenstein/Dankenstein/Book: Reanimation - DK" },
	[99259012] = { "@Dankenstein/Dankenstein/Winston: Save Point - DK" },
	[99259013] = { "@Dankenstein/Dankenstein/Chalice: Dankenstein - DK" },
	[99259014] = { "@Dankenstein/Dankenstein/Cleared: Dankenstein" },

	--Iron Slugger Boss
	[99260000] = { "@Iron Slugger/Iron Slugger/Book: Dankenstein Manual - IS" },
	[99260001] = { "@Iron Slugger/Iron Slugger/Cleared: Iron Slugger" },

	--Wulfrum Hall
	[99261000] = { "@Wulfrum Hall/Wulfrum/Key Item: Front Door Key - WH" },
	[99261001] = { "@Wulfrum Hall/Wulfrum/Life Bottle: Wulfrum Hall" },
	[99261002] = { "@Wulfrum Hall/Wulfrum/Equipment: Silver Shield Close To Vampire Room 2 - WH" },
	[99261003] = { "@Wulfrum Hall/Wulfrum/Energy Vial: Near Kitchen Stairs - WH" },
	[99261004] = { "@Wulfrum Hall/Wulfrum/Energy Vial: Left Room Of Entrance - WH" },
	[99261005] = { "@Wulfrum Hall/Wulfrum/Energy Vial: In Front Of Hall's Staircase - WH" },
	[99261006] = { "@Wulfrum Hall/Wulfrum/Gold Coins: Bag Left Side Of Entrance Stairs - WH" },
	[99261007] = { "@Wulfrum Hall/Wulfrum/Gold Coins: Chest Close To Vampire Room 1 - WH" },
	[99261008] = { "@Wulfrum Hall/Wulfrum/Gold Coins: Chest in Vampire Room 3 - WH" },
	[99261009] = { "@Wulfrum Hall/Wulfrum/Gold Coins: Bag in Vampire Room 5 - WH" },
	[99261010] = { "@Wulfrum Hall/Wulfrum/Winston: Level Start - WH" },
	[99261011] = { "@Wulfrum Hall/Wulfrum/Winston: Vampires - WH" },
	[99261012] = { "@Wulfrum Hall/Wulfrum/Chalice: Wulfrum Hall" },
	[99261013] = { "@Wulfrum Hall/Wulfrum/Cleared: Wulfrum Hall" },

	--The Count Boss
	[99262000] = { "@The Count/The Count/Winston: Level Start - TC" },
	[99262001] = { "@The Count/The Count/Gold Coins: Gold Chest - TC" },
	[99262002] = { "@The Count/The Count/Cleared: The Count" },

	--Whitechapel
	[99263000] = { "@Whitechapel/Whitechapel/Key Item: Library Key in House Basement - WC" },
	[99263001] = { "@Whitechapel/Whitechapel/Key Item: Griffin Shield - WC" },
	[99263002] = { "@Whitechapel/Whitechapel/Key Item: Membership Card - WC" },
	[99263003] = { "@Whitechapel/Whitechapel/Key Item: Elegant Suit - WC" },
	[99263004] = { "@Whitechapel/Whitechapel/Key Item: Unicorn Shield - WC" },
	[99263005] = { "@Whitechapel/Whitechapel/Key Item: Beard - WC" },
	[99263006] = { "@Whitechapel/Whitechapel/Life Bottle: Whitechapel" },
	[99263007] = { "@Whitechapel/Whitechapel/Equipment: Silver Shield in Library - WC" },
	[99263008] = { "@Whitechapel/Whitechapel/Equipment: Flaming Crossbow Inside House Near Unicorn Shield - WC" },
	[99263009] = { "@Whitechapel/Whitechapel/Gold Coins: Bag 1 in House Basement - WC" },
	[99263010] = { "@Whitechapel/Whitechapel/Gold Coins: Bag 2 in House Basement - WC" },
	[99263011] = { "@Whitechapel/Whitechapel/Gold Coins: Bag 1 Tailor Shop Basement -WC" },
	[99263012] = { "@Whitechapel/Whitechapel/Gold Coins: Bag 2 Tailor Shop Basement - WC" },
	[99263013] = { "@Whitechapel/Whitechapel/Gold Coins: Bag 3 Tailor Shop Basement - WC" },
	[99263014] = { "@Whitechapel/Whitechapel/Gold Coins: Chest Inside Club - WC" },
	[99263015] = { "@Whitechapel/Whitechapel/Book: Isibod Brunel - WC" },
	[99263016] = { "@Whitechapel/Whitechapel/Winston: Kiya Last Seen - WC" },
	[99263017] = { "@Whitechapel/Whitechapel/Chalice: Whitechapel - WC" },
	[99263018] = { "@Whitechapel/Whitechapel/Cleared: Whitechapel" },

	--The Sewers
	[99264000] = { "@The Sewers/The Sewers/Key Item: Poster - TS" },
	[99264001] = { "@The Sewers/The Sewers/Life Bottle: Sewers" },
	[99264002] = { "@The Sewers/The Sewers/Equipment: Gold Shield in Hub Area - TS" },
	[99264003] = { "@The Sewers/The Sewers/Event: Girls Freed - 1 - TS" },
	[99264004] = { "@The Sewers/The Sewers/Event: Girls Freed - 2 - TS" },
	[99264005] = { "@The Sewers/The Sewers/Event: Girls Freed - 3 - TS" },
	[99264006] = { "@The Sewers/The Sewers/Event: Girls Freed - 4 - TS" },
	[99264007] = { "@The Sewers/The Sewers/Event: Girls Freed - 5 - TS" },
	[99264008] = { "@The Sewers/The Sewers/Energy Vial: Vial 1 End Pipes Area - TS" },
	[99264009] = { "@The Sewers/The Sewers/Energy Vial: Vial 2 End Pipes Area - TS" },
	[99264010] = { "@The Sewers/The Sewers/Energy Vial: Vial 3 End Pipes Area - TS" },
	[99264011] = { "@The Sewers/The Sewers/Gold Coins: Bag at Pipes Area Start - TS" },
	[99264012] = { "@The Sewers/The Sewers/Gold Coins: Bag 1 in Pipes Puzzle Room - TS" },
	[99264013] = { "@The Sewers/The Sewers/Gold Coins: Bag 2 in Pipes Puzzle Room - TS" },
	[99264014] = { "@The Sewers/The Sewers/Gold Coins: Reward Chest 1 - TS" },
	[99264015] = { "@The Sewers/The Sewers/Gold Coins: Reward Chest 2 - TS" },
	[99264016] = { "@The Sewers/The Sewers/Winston: Save Point - TS" },
	[99264017] = { "@The Sewers/The Sewers/Winston: Something Really Interesting - TS" },
	[99264018] = { "@The Sewers/The Sewers/Chalice: Sewers" },
	[99264019] = { "@The Sewers/The Sewers/Cleared: The Sewers" },

	--The Time Machine
	[99265000] = { "@The Time Machine/The Time Machine/Key Item: Time Machine Piece - Planetarium - TTM" },
	[99265001] = { "@The Time Machine/The Time Machine/Key Item: Time Machine Piece - Grammar Horn - TTM" },
	[99265002] = { "@The Time Machine/The Time Machine/Key Item: Time Machine Piece - Moon Exhibit - TTM" },
	[99265003] = { "@The Time Machine/The Time Machine/Book: Space Beacon - TTM" },
	[99265004] = { "@The Time Machine/The Time Machine/Book: Grammar Horn - TTM" },
	[99265005] = { "@The Time Machine/The Time Machine/Book: Moon Exhibit - TTM" },
	[99265006] = { "@The Time Machine/The Time Machine/Book: The Time Machine" },
	[99265007] = { "@The Time Machine/The Time Machine/Winston: Entrance - TTM" },
	[99265008] = { "@The Time Machine/The Time Machine/Cleared: The Time Machine" },

	-- The Time Machine, The Sewers
	[99266000] = { "@The Time Machine, The Sewers/Sewers TM/Key Item: Time Stone - Hut Trap - TTMTS" },
	[99266001] = { "@The Time Machine, The Sewers/Sewers TM/Key Item: King Mullocks Key - Downing King - TTMTS" },
	[99266002] = { "@The Time Machine, The Sewers/Sewers TM/Equipment: Good Lightning - Changing Room - TTMTS" },
	[99266003] = { "@The Time Machine, The Sewers/Sewers TM/Winston: Entrance - TTMTS" },
	[99266004] = { "@The Time Machine, The Sewers/Sewers TM/Winston: Kings Hat - TTMTS" },
	[99266005] = { "@The Time Machine, The Sewers/Sewers TM/Winston: Stealing Time Stone - TTMTS" },
	[99266006] = { "@The Time Machine, The Sewers/Sewers TM/Cleared: The Time Machine, The Sewers" },

	--The Ripper
	[99267000] = { "@The Ripper/The Ripper/Winston: Entrance - TR" },
	[99267001] = { "@The Ripper/The Ripper/Cleared: The Ripper" },


	--Cathedral Spires
	[99268000] = { "@Cathedral Spires/Cathedral Spires/Key Item: Lost Soul - Bottom left of Cathedral - CS" },
	[99268001] = { "@Cathedral Spires/Cathedral Spires/Key Item: Lost Soul - Top of Cathedral - CS" },
	[99268002] = { "@Cathedral Spires/Cathedral Spires/Key Item: Lost Soul - Left Chapel on the Roo - CS" },
	[99268003] = { "@Cathedral Spires/Cathedral Spires/Key Item: Lost Soul - Right Chapel on the Roo - CS" },
	[99268004] = { "@Cathedral Spires/Cathedral Spires/Key Item: Lost Soul - Next to Life Bottle - CS" },
	[99268005] = { "@Cathedral Spires/Cathedral Spires/Life Bottle: Cathedral Spires" },
	[99268006] = { "@Cathedral Spires/Cathedral Spires/Equipment: Gold Shield in Chest at Start - CS" },
	[99268007] = { "@Cathedral Spires/Cathedral Spires/Equipment: Silver Shield Chest near Gold Coins - CS" },
	[99268008] = { "@Cathedral Spires/Cathedral Spires/Energy Vial: Next to Spiv - CS" },
	[99268009] = { "@Cathedral Spires/Cathedral Spires/Gold Coins: Bottom Right Near Spiv - CS" },
	[99268010] = { "@Cathedral Spires/Cathedral Spires/Gold Coins: Chest After First Lost Soul - CS" },
	[99268011] = { "@Cathedral Spires/Cathedral Spires/Gold Coins: Chest After First Flame Gargoyles - CS" },
	[99268012] = { "@Cathedral Spires/Cathedral Spires/Gold Coins: Chest Near Silver Shield Chest - CS" },
	[99268013] = { "@Cathedral Spires/Cathedral Spires/Gold Coins: Bag at top of Spire - CS" },
	[99268014] = { "@Cathedral Spires/Cathedral Spires/Winston: Entrance - CS" },
	[99268015] = { "@Cathedral Spires/Cathedral Spires/Cleared: Cathedral Spires" },


	--Cathedral Spires, The Descent
	[99269000] = { "@Cathedral Spires, The Descent/The Descent/Key Item: Lost Soul - Left Jump at Chandelere - CSTD" },
	[99269001] = { "@Cathedral Spires, The Descent/The Descent/Key Item: Lost Soul - Right Jump at Chandelere - CSTD" },
	[99269002] = { "@Cathedral Spires, The Descent/The Descent/Key Item: Lost Soul - Demon Statue Mausoleum - CSTD" },
	[99269003] = { "@Cathedral Spires, The Descent/The Descent/Key Item: Lost Soul - Entrance Room - CSTD" },
	[99269004] = { "@Cathedral Spires, The Descent/The Descent/Key Item: Lost Soul - Top of Pully Front - CSTD" },
	[99269005] = { "@Cathedral Spires, The Descent/The Descent/Key Item: Lost Soul - Top of Pully Back - CSTD" },
	[99269006] = { "@Cathedral Spires, The Descent/The Descent/Key Item: Lost Soul - Pully Room Right - CSTD" },
	[99269007] = { "@Cathedral Spires, The Descent/The Descent/Key Item: Golden Cog in Room - CSTD" },
	[99269008] = { "@Cathedral Spires, The Descent/The Descent/Key Item: Golden Cog in Hand Area - CSTD" },
	[99269009] = { "@Cathedral Spires, The Descent/The Descent/Key Item: Spell Page - Demon Death - CSTD" },
	[99269010] = { "@Cathedral Spires, The Descent/The Descent/Life Bottle: Cathedral Spires, The Decent" },
	[99269011] = { "@Cathedral Spires, The Descent/The Descent/Gold Coins: Golden Cog Room Entrance - CSTD" },
	[99269012] = { "@Cathedral Spires, The Descent/The Descent/Gold Coins: Golden Cog Room Bottom - CSTD" },
	[99269013] = { "@Cathedral Spires, The Descent/The Descent/Winston: Entrance - CSTD" },
	[99269014] = { "@Cathedral Spires, The Descent/The Descent/Cleared: Cathedral Spires, The Descent" },

	--The Demon Boss
	[99270000] = { "@The Demon/The Demon/Winston: Entrance - TD" },
	[99270001] = { "@The Demon/The Demon/Cleared: The Demon" }



}
