Tracker:AddLocations("locations/Overworld.json")
Tracker:AddLocations("locations/The Tomb.json")
Tracker:AddLocations("locations/The Museum.json")
Tracker:AddLocations("locations/Kensington.json")
Tracker:AddLocations("locations/Freakshow.json")
Tracker:AddLocations("locations/Greenwich.json")
Tracker:AddLocations("locations/Kew Gardens.json")
Tracker:AddLocations("locations/Dankenstein.json")
Tracker:AddLocations("locations/Wulfrum Hall.json")
Tracker:AddLocations("locations/Whitechapel.json")