Tracker:AddLocations("locations/Overworld.json")
Tracker:AddLocations("locations/The Tomb.json")
Tracker:AddLocations("locations/The Museum.json")
Tracker:AddLocations("locations/Kensington.json")
Tracker:AddLocations("locations/Freakshow.json")
Tracker:AddLocations("locations/Greenwich.json")
Tracker:AddLocations("locations/Kew Gardens.json")
Tracker:AddLocations("locations/Dankenstein.json")
Tracker:AddLocations("locations/Wulfrum Hall.json")
Tracker:AddLocations("locations/Whitechapel.json")
Tracker:AddLocations("locations/Sewers.json")
Tracker:AddLocations("locations/Time Machine.json")
Tracker:AddLocations("locations/Sewers TM.json")
Tracker:AddLocations("locations/Cathedral.json")
Tracker:AddLocations("locations/Descent.json")